apiVersion: v1
kind: Service
metadata:
  name: youtubeapp-service
  labels:
    app: youtubeapp
spec:
  selector:
    app: youtubeapp

  ports:
    - port: 3000
      targetPort: 3000

  type: LoadBalancer
