apiVersion: v1
kind: Service
metadata:
  name: youtubeapp-service
  labels:
    app: youtubeapp
spec:
  selector:
    app: youtubeapp

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
